export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dde4e5",
        "surface-container-high": "#e4e9ea",
        "on-secondary-fixed": "#2f4436",
        "on-tertiary-fixed": "#454b48",
        "on-secondary-container": "#415748",
        "background": "#ffffff",
        "primary-fixed-dim": "#d4d4d4",
        "surface": "#ffffff",
        "surface-container-low": "#f8f9f9",
        "on-tertiary": "#f5faf6",
        "tertiary-container": "#f0f5f1",
        "on-background": "#000000",
        "primary-dim": "#1a1a1a",
        "tertiary-fixed": "#f0f5f1",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "secondary-fixed": "#d0e9d5",
        "on-error": "#fff7f6",
        "on-primary-fixed": "#3f3f3f",
        "tertiary-fixed-dim": "#e1e7e3",
        "inverse-surface": "#000000",
        "primary-fixed": "#e2e2e2",
        "on-primary-container": "#525252",
        "secondary": "#1B3022",
        "on-tertiary-fixed-variant": "#626764",
        "tertiary-dim": "#4f5452",
        "secondary-dim": "#425849",
        "outline": "#000000",
        "surface-variant": "#f2f2f2",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary": "#000000",
        "on-primary-fixed-variant": "#5b5b5b",
        "on-tertiary-container": "#2f4436",
        "on-surface-variant": "#666666",
        "secondary-fixed-dim": "#c2dbc7",
        "surface-container": "#f2f2f2",
        "on-primary": "#ffffff",
        "surface-bright": "#ffffff",
        "primary-container": "#000000",
        "surface-tint": "#000000",
        "surface-dim": "#e5e5e5",
        "on-secondary-fixed-variant": "#4b6151",
        "secondary-container": "#d0e9d5",
        "tertiary": "#1B3022",
        "error": "#b91c1c",
        "on-error-container": "#450a0a",
        "on-surface": "#000000",
        "outline-variant": "#e5e5e5",
        "inverse-primary": "#ffffff",
        "inverse-on-surface": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
